### ISSUE TITLE
Napisać funkcję do rekursywnego analizowania drzewa biblioteki muzycznej.

### ISSUE THREAD

**Issue by mRokita** [mRokita/sMusic-core#1]
#### Parametry funkcji:
- lista ścieżek do przeanalizowania 
#### Funkcja powinna zwracać dane o bibliotece w formacie podobnym do tego:

``` python
{
    "marilynmanson": [
        "Marilyn Manson",
        {
            "thepaleemperor": [
                "The Pale Emperor",
                {
                    "warshipmywreck": {
                                       "title": "Warship My Wreck",
                                       "album": "The Pale Emperor",
                                       "genre": "Heavy Metal",
                                       "year": "2015",
                                       "musicbrainz_id": "SDSJglkajlkdjgsiIW",
                                       "track_id": 1,
                                       "path": "/music/w.mp3"
                                       },
                     "deepsix": {
                                       "title": "Deep Six",
                                       "album": "The Pale Emperor",
                                       "genre": "Heavy Metal",
                                       "year": "2015",
                                       "musicbrainz_id": "SDSJglkajlkdjgsiIW",
                                       "track_id": 2,
                                       "path": "/music/a.mp3"
                                       }
                }
            ]
        }
    ]
}
```

Klucze słownika powinny być złożone ze znaków lowercase i zawierać tylko znaki zawarte w "abcdefghijklmnopqrstuvxyz0123456789".
Trudniejsze przypadki do rozwiązania:
- Plik nie ma tagów ID3
- String przekształcany na klucz ma tylko znaki poza "abcdefghijklmnopqrstuvxyz0123456789"

**Comment by s17k** [comment]
Będę pomijał wszystkie znaki w nazwach poza "abcdefghijlklmnopqrstuvxyz1234567890"

**Comment by mRokita** [comment]
@stasszczesniak oczywiście najpierw wywołaj string.lower() :)

**Comment by cytadela8** [comment]
Trzeba rozpatrzyć, co jeśli są dwa pliki o identycznym kluczu, ale różnej nazwie. Proponuję jakoś chamsko dopisywać coś do klucza.

**Comment by s17k** [comment]
mogę dodawać na koniec po prostu hasha unicodowej nazwy

**Comment by mRokita** [comment]
@stasszczesniak pamietaj, że będzie funkcja wyszukiwania, fajnie by było też, gdyby się dało normalizować polskie znaki na zasadzie "ąłóęńćżź" > "aloenczz"

**Comment by s17k** [comment]
@mRokita ok, będzie zrobione. Dzisiaj trochę chory byłem i jeszcze GCI mam, więc jutro pewnie, bo do szkoły nie idę.

**Comment by mRokita** [comment]
@stasszczesniak k, powodzenia z GCI :)
