### ISSUE TITLE
TeamSpeak

### ISSUE THREAD

**Issue by cytadela8** [mRokita/sMusic-core#10]
Można ogarnąć TeamSpeak-a. Co się dzieje z KLUB-owym TeamSpeakiem? Mam też dostęp do mało używanego kanału kolegi. Można tworzyć podkanały tam z tego co pamiętam. Jednak najlepiej było by ogarnąć KLUB-owego. Mam tam własny kanał. Joachim Kowalewski odpowiada za TeamSpeaka KLUB. Co wy na to?

**Comment by s17k** [comment]
Zrobiłem już kanał IRC na freenodzie. #staszic-music, wbijajcie

**Comment by cytadela8** [comment]
TeamSpeak != Freenode
Nienawidzę pisać.

**Comment by s17k** [comment]
Możemy nie używać IRC, tylko Slacka - co o tym myślicie ?

**Comment by cytadela8** [comment]
nie znam się

**Comment by s17k** [comment]
też nie, IRC > Slack, never mind

**Comment by s17k** [comment]
Nie ma sensu robić TeamSpeaka.
Nie ma możliwości czytania logów, a oglądać nikt nie chce.

**Comment by mRokita** [comment]
Proponuję IRC na freenode, mogę zasponsorować bouncery, chyba jeszcze mogę (oni mają limit do 5 połączeń z jednego IP chyba, więc Artur się zmieści :P)

**Comment by s17k** [comment]
mRokita: pamiętaj, że IRC już jest: staszic-music na freenode

**Comment by cytadela8** [comment]
@stasszczesniak: TeamSpeak też jest, tylko trzeba znaleźć

**Comment by mRokita** [comment]
@cytadela8 ts3 moge postawić, ale mam ostatnio troche mało mocy na serwerze

**Comment by cytadela8** [comment]
@mRokita przecież piszę, że już ts3 tylko trzeba znaleźć
