### ISSUE TITLE
Stwórzmy jakąś organizację na GitHubie typu "Staszicode"

### ISSUE THREAD

**Issue by cytadela8** [mRokita/sMusic-core#11]
Fajnie by było mieć link typu "github.com/Staszicode/sMusic-core". Również to ogólnie będzie wyglądało lepiej na przyszłość. Zważywszy szczególnie jeśli chcemy mieć więcej niż jedno repo, a tak sugeruje nazwa.

**Comment by s17k** [comment]
Stworzona, Michał musi tylko zrobić na nią transfer ownership.

**Comment by cytadela8** [comment]
jak się nazywa i czemu mnie tam nie ma? :stuck_out_tongue:

**Comment by s17k** [comment]
https://github.com/StaszicCode
Wysłałem do was zaproszenia.

**Comment by mRokita** [comment]
k, przeniosłem repo
