### ISSUE TITLE
Kartka na drzwiach radiowęzła

### ISSUE THREAD

**Issue by cytadela8** [mRokita/sMusic-core#12]
Umieśmy jakąś kartkę na drzwiach radiowęzła z naszymi nazwiskami i kontaktem:
"Staszic Music
to pomieszczenie już niefunkcjonuje, niedługo wszystkie funkcjonalności będą dostępne przez aplikację web-ową
Administratorzy:
Michał Rokita (mail)
Artur Puzio (ert@staszic.waw.pl)
Stanisław Szcześniak (stas.szczesniak@gmail.com)
kontakt również na kanale IRC: #staszic-music@freenode
repozytorium oprogramowania: github.com/StaszicCode/sMusic-core"

**Comment by s17k** [comment]
Spróbuje zrobić taką kartkę jutro, chyba że ktoś inny chce, to odstąpie.

**Comment by cytadela8** [comment]
:+1: Możesz mi rzucić plika to wydrukuję, lub wydrukować w bibliotece

**Comment by mRokita** [comment]
Ja to zrobię, mam drukarkę i taśmę w serwerowni ;)

**Comment by mRokita** [comment]
zrobiłem alias radio@mrokita.pl, łatwiej będzie ogarnąć ewentualny spam i będzie łatwiej ogarniać wiadomości od ludzi zespołowo używając reply to all :)

**Comment by mRokita** [comment]
Powiesiłem kartkę na drzwiach 127
