### ISSUE TITLE
drobna sugestia do kodu

### ISSUE THREAD

**Issue by cytadela8** [mRokita/sMusic-core#13]
[github.com/StaszicCode/sMusic-core/blob/master/cmus_utils.py#L97](github.com/StaszicCode/sMusic-core/blob/master/cmus_utils.py#L97)
nie powinniśmy przechowywać danych w `/tmp` maszyna może ulec reboot-owi. To może zrobić problemy. Powinniśmy ustalić stosowną ścieżkę dla danych serwera. Może w folderze `~/.smusic`

**Comment by mRokita** [comment]
To jest plik tymczasowy, jest usuwany po ułamku sekundy, kiedy CMUS go załaduje ;)
~/.smusic może być ok do configow, ale tez nie jestem pewien czy na pewno tam.

**Comment by cytadela8** [comment]
a jak może być skasowany to ok
