### ISSUE TITLE
Zrobić moduł do cmus-remote z kilkoma funkcjami

### ISSUE THREAD

**Issue by mRokita** [mRokita/sMusic-core#2]
Funkcje:
- load_queue(path) - załadowanie kolejki z playlisty
- player_pause()
- player_play()
- player_stop()
- player_next()
- player_prev()
- update_playlist(path) - znajduje aktualny utwór w nowej playliście, czyści kolejkę i dodaje następne utwory
- get_player_status() - zwraca informacje o aktualnym utworze

**Comment by cytadela8** [comment]
Proponuję, abyś się wstrzymał z tym dopóki nie uzgodnimy protokołu, jako że moduł do cmusa będzie wyłącznie realizował protokół z tego co rozumiem. Osobiście nie tworzyłbym funkcji: player_next(), player_prev(), a update_playlist miałby wyłącznie dodawać utwory (prawdopodobnie upewniając się, że pierwszy nie jest aktualnie odtwarzany i w takiej sytuacji wywalając go)
