### ISSUE TITLE
Minimalny Serwer

### ISSUE THREAD

**Issue by cytadela8** [mRokita/sMusic-core#8]
Serwer funkcjonuje jako "proxy" między webservice-em a radiowęzłami (radiowęzły łączą się do serwera i webservice łączy się do serwera). Głównym zadaniem Serwera jest kolejkowanie zapytań i odsyłanie odpowiedzi do odpowiednich instancji webservice-u.
- [x] serwer TCP dla radiowęzła czeka na połączenie i przesyła dane od API do wszystkich połączonych klientów (zabezpieczenia uważam za nie potrzebne na tej fazie, brak interpretacji odpowiedzi klientów)
- [x] serwer TCP dla webservice-u czeka na połączenia z localhost i przesyła do radiowęzłów.
- [x] pobieranie informacji o radiowęźle przy użyciu polecenia "ping"

**Comment by mRokita** [comment]
https://github.com/StaszicCode/sMusic-www/blob/master/core_server.py
https://github.com/StaszicCode/sMusic-core/blob/master/core_client.py

Zaimplementowałem podstawy protokołu.
